#!/bin/bash

homedir="/home" #
secs=10 # Seconds before user is logged out
if [ -z $1 ] ; then
echo "Usage: $0 account" >&2
exit 1
elif [ "$(id -un)" != "root" ] ; then
echo "Error. You must be 'root' to run this command." >&2
exit 1
fi
echo "Please change the password for account $1 to something new."
passwd $1
if who|grep "$1" > /dev/null ; then
for tty in $(who | grep $1 | awk '{print $2}'); do
cat << "EOF" > /dev/$tty

done
echo "(Warned $1, now sleeping $secs seconds)"
sleep $secs

System Administration: Managing Users 135

jobs=$(ps -u $1 | cut -d\ -f1)
X kill -s HUP $jobs .
sleep 1 # Give it a second...
Y kill -s KILL $jobs > /dev/null 2>1 
echo "$1 was logged in. Just logged them out."
fi
# Finally, let's close off their home directory from prying eyes.
chmod 000 $homedir/$1
echo "Account $1 has been suspended."
exit 0
